version: "3.8"

services:
  web:
    build:
      context: ./itsp_team_making
      dockerfile: Dockerfile
    container_name: itsp-team-making-web
    restart: unless-stopped
    ports:
      - "3008:4736"
