version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: itsp_team_making/Dockerfile
    container_name: itsp-team-making-web
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      PORT: 4736
    ports:
      - "3008:4736"
